AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'vendor/**/*'
    - 'public/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Rails/Output:
  Include:
    - app/**/*.rb
    - db/**/*.rb

Rails/Validation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

# http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment
# http://d.hatena.ne.jp/ku-ma-me/20151004/p1
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Performance/Count:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Performance/Count:
  Enabled: false

Performance/RedundantMatch:
  Enabled: false
